/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "rtl/lfsr_nfsr_top.v:5.1-53.10" *)
module lfsr_nfsr_top(clk, rst, plaintext, ciphertext, decrypted_text);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  (* src = "rtl/lfsr_nfsr_top.v:13.16-13.17" *)
  wire [7:0] L;
  (* src = "rtl/lfsr_nfsr_top.v:14.16-14.17" *)
  wire [7:0] N;
  (* src = "rtl/lfsr_nfsr_top.v:15.10-15.11" *)
  wire Z;
  (* src = "rtl/lfsr_nfsr_top.v:9.17-9.27" *)
  output ciphertext;
  wire ciphertext;
  (* src = "rtl/lfsr_nfsr_top.v:6.17-6.20" *)
  input clk;
  wire clk;
  (* hdlname = "dec_inst Z" *)
  (* src = "rtl/lfsr_nfsr_top.v:47.13-51.6|rtl/decrypt.v:8.17-8.18" *)
  wire \dec_inst.Z ;
  (* hdlname = "dec_inst ciphertext" *)
  (* src = "rtl/lfsr_nfsr_top.v:47.13-51.6|rtl/decrypt.v:7.17-7.27" *)
  wire \dec_inst.ciphertext ;
  (* hdlname = "dec_inst plaintext_out" *)
  (* src = "rtl/lfsr_nfsr_top.v:47.13-51.6|rtl/decrypt.v:9.17-9.30" *)
  wire \dec_inst.plaintext_out ;
  (* src = "rtl/lfsr_nfsr_top.v:10.17-10.31" *)
  output decrypted_text;
  wire decrypted_text;
  (* hdlname = "enc_inst Z" *)
  (* src = "rtl/lfsr_nfsr_top.v:40.13-44.6|rtl/encrypt.v:8.17-8.18" *)
  wire \enc_inst.Z ;
  (* hdlname = "enc_inst ciphertext" *)
  (* src = "rtl/lfsr_nfsr_top.v:40.13-44.6|rtl/encrypt.v:9.17-9.27" *)
  wire \enc_inst.ciphertext ;
  (* hdlname = "enc_inst plaintext" *)
  (* src = "rtl/lfsr_nfsr_top.v:40.13-44.6|rtl/encrypt.v:7.17-7.26" *)
  wire \enc_inst.plaintext ;
  (* hdlname = "ks_inst L" *)
  (* src = "rtl/lfsr_nfsr_top.v:33.15-37.6|rtl/keystream.v:7.23-7.24" *)
  wire [7:0] \ks_inst.L ;
  (* hdlname = "ks_inst N" *)
  (* src = "rtl/lfsr_nfsr_top.v:33.15-37.6|rtl/keystream.v:8.23-8.24" *)
  wire [7:0] \ks_inst.N ;
  (* hdlname = "ks_inst Z" *)
  (* src = "rtl/lfsr_nfsr_top.v:33.15-37.6|rtl/keystream.v:9.17-9.18" *)
  wire \ks_inst.Z ;
  (* hdlname = "lfsr_inst L" *)
  (* src = "rtl/lfsr_nfsr_top.v:18.10-22.6|rtl/LFSR.v:9.23-9.24" *)
  wire [7:0] \lfsr_inst.L ;
  (* hdlname = "lfsr_inst clk" *)
  (* src = "rtl/lfsr_nfsr_top.v:18.10-22.6|rtl/LFSR.v:7.17-7.20" *)
  wire \lfsr_inst.clk ;
  (* hdlname = "lfsr_inst rst" *)
  (* src = "rtl/lfsr_nfsr_top.v:18.10-22.6|rtl/LFSR.v:8.17-8.20" *)
  wire \lfsr_inst.rst ;
  (* hdlname = "nfsr_inst L4" *)
  (* src = "rtl/lfsr_nfsr_top.v:25.10-30.6|rtl/NFSR.v:9.17-9.19" *)
  wire \nfsr_inst.L4 ;
  (* hdlname = "nfsr_inst N" *)
  (* src = "rtl/lfsr_nfsr_top.v:25.10-30.6|rtl/NFSR.v:10.23-10.24" *)
  wire [7:0] \nfsr_inst.N ;
  (* hdlname = "nfsr_inst clk" *)
  (* src = "rtl/lfsr_nfsr_top.v:25.10-30.6|rtl/NFSR.v:7.17-7.20" *)
  wire \nfsr_inst.clk ;
  (* hdlname = "nfsr_inst rst" *)
  (* src = "rtl/lfsr_nfsr_top.v:25.10-30.6|rtl/NFSR.v:8.17-8.20" *)
  wire \nfsr_inst.rst ;
  (* src = "rtl/lfsr_nfsr_top.v:8.17-8.26" *)
  input plaintext;
  wire plaintext;
  (* src = "rtl/lfsr_nfsr_top.v:7.17-7.20" *)
  input rst;
  wire rst;
  XOR2_X1 _049_ (
    .A(ciphertext),
    .B(\dec_inst.Z ),
    .Z(decrypted_text)
  );
  XOR2_X1 _050_ (
    .A(plaintext),
    .B(\dec_inst.Z ),
    .Z(ciphertext)
  );
  NAND2_X1 _051_ (
    .A1(\lfsr_inst.L [7]),
    .A2(\nfsr_inst.N [4]),
    .ZN(_002_)
  );
  XOR2_X1 _052_ (
    .A(\lfsr_inst.L [2]),
    .B(\nfsr_inst.N [3]),
    .Z(_003_)
  );
  XNOR2_X1 _053_ (
    .A(_002_),
    .B(_003_),
    .ZN(_000_)
  );
  NAND2_X1 _054_ (
    .A1(\lfsr_inst.L [1]),
    .A2(\nfsr_inst.N [6]),
    .ZN(_001_)
  );
  XNOR2_X1 _055_ (
    .A(_000_),
    .B(_001_),
    .ZN(\dec_inst.Z )
  );
  INV_X1 _056_ (
    .A(\lfsr_inst.L [0]),
    .ZN(_012_)
  );
  INV_X1 _057_ (
    .A(\lfsr_inst.L [3]),
    .ZN(_013_)
  );
  INV_X1 _058_ (
    .A(\lfsr_inst.L [5]),
    .ZN(_014_)
  );
  XOR2_X1 _059_ (
    .A(\lfsr_inst.L [5]),
    .B(\lfsr_inst.L [7]),
    .Z(_015_)
  );
  XNOR2_X1 _060_ (
    .A(\lfsr_inst.L [3]),
    .B(\lfsr_inst.L [4]),
    .ZN(_016_)
  );
  XNOR2_X1 _061_ (
    .A(_015_),
    .B(_016_),
    .ZN(_017_)
  );
  OR2_X1 _062_ (
    .A1(rst),
    .A2(_017_),
    .ZN(_004_)
  );
  NOR2_X1 _063_ (
    .A1(rst),
    .A2(_012_),
    .ZN(_005_)
  );
  OR2_X1 _064_ (
    .A1(rst),
    .A2(\lfsr_inst.L [1]),
    .ZN(_006_)
  );
  OR2_X1 _065_ (
    .A1(rst),
    .A2(\lfsr_inst.L [2]),
    .ZN(_007_)
  );
  NOR2_X1 _066_ (
    .A1(rst),
    .A2(_013_),
    .ZN(_008_)
  );
  OR2_X1 _067_ (
    .A1(rst),
    .A2(\lfsr_inst.L [4]),
    .ZN(_009_)
  );
  NOR2_X1 _068_ (
    .A1(rst),
    .A2(_014_),
    .ZN(_010_)
  );
  OR2_X1 _069_ (
    .A1(rst),
    .A2(\lfsr_inst.L [6]),
    .ZN(_011_)
  );
  (* src = "rtl/lfsr_nfsr_top.v:18.10-22.6|rtl/LFSR.v:16.5-21.8" *)
  DFF_X1 _070_ (
    .CK(clk),
    .D(_004_),
    .Q(\lfsr_inst.L [0]),
    .QN(_025_)
  );
  (* src = "rtl/lfsr_nfsr_top.v:18.10-22.6|rtl/LFSR.v:16.5-21.8" *)
  DFF_X1 _071_ (
    .CK(clk),
    .D(_005_),
    .Q(\lfsr_inst.L [1]),
    .QN(_024_)
  );
  (* src = "rtl/lfsr_nfsr_top.v:18.10-22.6|rtl/LFSR.v:16.5-21.8" *)
  DFF_X1 _072_ (
    .CK(clk),
    .D(_006_),
    .Q(\lfsr_inst.L [2]),
    .QN(_023_)
  );
  (* src = "rtl/lfsr_nfsr_top.v:18.10-22.6|rtl/LFSR.v:16.5-21.8" *)
  DFF_X1 _073_ (
    .CK(clk),
    .D(_007_),
    .Q(\lfsr_inst.L [3]),
    .QN(_022_)
  );
  (* src = "rtl/lfsr_nfsr_top.v:18.10-22.6|rtl/LFSR.v:16.5-21.8" *)
  DFF_X1 _074_ (
    .CK(clk),
    .D(_008_),
    .Q(\lfsr_inst.L [4]),
    .QN(_021_)
  );
  (* src = "rtl/lfsr_nfsr_top.v:18.10-22.6|rtl/LFSR.v:16.5-21.8" *)
  DFF_X1 _075_ (
    .CK(clk),
    .D(_009_),
    .Q(\lfsr_inst.L [5]),
    .QN(_020_)
  );
  (* src = "rtl/lfsr_nfsr_top.v:18.10-22.6|rtl/LFSR.v:16.5-21.8" *)
  DFF_X1 _076_ (
    .CK(clk),
    .D(_010_),
    .Q(\lfsr_inst.L [6]),
    .QN(_019_)
  );
  (* src = "rtl/lfsr_nfsr_top.v:18.10-22.6|rtl/LFSR.v:16.5-21.8" *)
  DFF_X1 _077_ (
    .CK(clk),
    .D(_011_),
    .Q(\lfsr_inst.L [7]),
    .QN(_018_)
  );
  INV_X1 _078_ (
    .A(\nfsr_inst.N [1]),
    .ZN(_034_)
  );
  INV_X1 _079_ (
    .A(\nfsr_inst.N [4]),
    .ZN(_035_)
  );
  NAND2_X1 _080_ (
    .A1(\nfsr_inst.N [3]),
    .A2(\nfsr_inst.N [5]),
    .ZN(_036_)
  );
  XOR2_X1 _081_ (
    .A(\nfsr_inst.N [7]),
    .B(_036_),
    .Z(_037_)
  );
  NAND2_X1 _082_ (
    .A1(\nfsr_inst.N [1]),
    .A2(\nfsr_inst.N [2]),
    .ZN(_038_)
  );
  XOR2_X1 _083_ (
    .A(\lfsr_inst.L [4]),
    .B(_038_),
    .Z(_039_)
  );
  XNOR2_X1 _084_ (
    .A(_037_),
    .B(_039_),
    .ZN(_040_)
  );
  NOR2_X1 _085_ (
    .A1(rst),
    .A2(_040_),
    .ZN(_026_)
  );
  OR2_X1 _086_ (
    .A1(rst),
    .A2(\nfsr_inst.N [0]),
    .ZN(_027_)
  );
  NOR2_X1 _087_ (
    .A1(rst),
    .A2(_034_),
    .ZN(_028_)
  );
  OR2_X1 _088_ (
    .A1(rst),
    .A2(\nfsr_inst.N [2]),
    .ZN(_029_)
  );
  OR2_X1 _089_ (
    .A1(rst),
    .A2(\nfsr_inst.N [3]),
    .ZN(_030_)
  );
  NOR2_X1 _090_ (
    .A1(rst),
    .A2(_035_),
    .ZN(_031_)
  );
  OR2_X1 _091_ (
    .A1(rst),
    .A2(\nfsr_inst.N [5]),
    .ZN(_032_)
  );
  OR2_X1 _092_ (
    .A1(rst),
    .A2(\nfsr_inst.N [6]),
    .ZN(_033_)
  );
  (* src = "rtl/lfsr_nfsr_top.v:25.10-30.6|rtl/NFSR.v:22.5-27.8" *)
  DFF_X1 _093_ (
    .CK(clk),
    .D(_026_),
    .Q(\nfsr_inst.N [0]),
    .QN(_048_)
  );
  (* src = "rtl/lfsr_nfsr_top.v:25.10-30.6|rtl/NFSR.v:22.5-27.8" *)
  DFF_X1 _094_ (
    .CK(clk),
    .D(_027_),
    .Q(\nfsr_inst.N [1]),
    .QN(_047_)
  );
  (* src = "rtl/lfsr_nfsr_top.v:25.10-30.6|rtl/NFSR.v:22.5-27.8" *)
  DFF_X1 _095_ (
    .CK(clk),
    .D(_028_),
    .Q(\nfsr_inst.N [2]),
    .QN(_046_)
  );
  (* src = "rtl/lfsr_nfsr_top.v:25.10-30.6|rtl/NFSR.v:22.5-27.8" *)
  DFF_X1 _096_ (
    .CK(clk),
    .D(_029_),
    .Q(\nfsr_inst.N [3]),
    .QN(_045_)
  );
  (* src = "rtl/lfsr_nfsr_top.v:25.10-30.6|rtl/NFSR.v:22.5-27.8" *)
  DFF_X1 _097_ (
    .CK(clk),
    .D(_030_),
    .Q(\nfsr_inst.N [4]),
    .QN(_044_)
  );
  (* src = "rtl/lfsr_nfsr_top.v:25.10-30.6|rtl/NFSR.v:22.5-27.8" *)
  DFF_X1 _098_ (
    .CK(clk),
    .D(_031_),
    .Q(\nfsr_inst.N [5]),
    .QN(_043_)
  );
  (* src = "rtl/lfsr_nfsr_top.v:25.10-30.6|rtl/NFSR.v:22.5-27.8" *)
  DFF_X1 _099_ (
    .CK(clk),
    .D(_032_),
    .Q(\nfsr_inst.N [6]),
    .QN(_042_)
  );
  (* src = "rtl/lfsr_nfsr_top.v:25.10-30.6|rtl/NFSR.v:22.5-27.8" *)
  DFF_X1 _100_ (
    .CK(clk),
    .D(_033_),
    .Q(\nfsr_inst.N [7]),
    .QN(_041_)
  );
  assign \lfsr_inst.rst  = rst;
  assign \lfsr_inst.clk  = clk;
  assign \nfsr_inst.rst  = rst;
  assign \nfsr_inst.clk  = clk;
  assign \nfsr_inst.L4  = \lfsr_inst.L [4];
  assign \ks_inst.L  = \lfsr_inst.L ;
  assign \ks_inst.N  = \nfsr_inst.N ;
  assign \ks_inst.Z  = \dec_inst.Z ;
  assign \enc_inst.Z  = \dec_inst.Z ;
  assign \enc_inst.ciphertext  = ciphertext;
  assign \enc_inst.plaintext  = plaintext;
  assign \dec_inst.ciphertext  = ciphertext;
  assign \dec_inst.plaintext_out  = decrypted_text;
  assign L = \lfsr_inst.L ;
  assign N = \nfsr_inst.N ;
  assign Z = \dec_inst.Z ;
endmodule
